case: 9.5

dataset:
  type: ST2D
  data_file: data/preprocessed_data/${case}.h5ad
  val_proportion: 0.2
  keep_ratio: True

pipeline:
  embedder:
    model: AE
    dim_hidden: [2048, 512, 64]
    dim_latent: 32

  optimization:
    seed: 8848
    epochs: 200
    lr: 1e-5
    val_freq: 50
    logs: logs/AE/${case}
    batch_size: 512
  
  predict_mode: all
  embedded_data: embedded-all.h5ad
