case: 9.5

dataset:
  type: ST2D
  data_file: data/preprocessed_data/${case}.h5ad
  val_proportion: 0.2
  keep_ratio: True

pipeline:
  target: raw_representations

  inr:
    model: FFN
    num_hidden_layers: 12
    num_hidden_features: 2048 
    phase: #None if using vanilla INR
    decoder: # will be automatically updated

  optimization:
    seed: 8848
    epochs: 2000
    lr: 1e-5
    val_freq: 200
    logs: logs/FFN/${case}
    batch_size: 8192

  predict_mode: val 
  reconstructed_data: reconstructed-val.h5ad