dataset:
  type: ST2D
  data_file: /data/datasets/SUICA_data/ST2D/PCA-E13.5_E1S1.MOSTA.h5ad
  val_proportion: 0.2
  keep_ratio: True

pipeline:
  target: embeddings

  inr:
    model: SIREN
    num_hidden_layers: 12
    num_hidden_features: 2048 
    decoder:
      
  optimization:
    seed: 8848
    epochs: 2000
    lr: 1e-5
    val_freq: 100
    logs: logs/inr_pca_13.5
    batch_size: 8192

  predict_mode: val
  reconstructed_data: reconstructed-E13.5_E1S1.MOSTA.h5ad